#!/bin/bash

set -e

# Stop service before removal if it's running
if systemctl is-active --quiet tproxy.service; then
    systemctl stop tproxy.service
fi

# Disable service
systemctl disable tproxy.service